blog/urls.py
from django.conf.urls import url, include
from django.views.generic import ListView, DetailView
from blog.models import Post, Category
from . import views



urlpatterns = [ url(r'^$', ListView.as_view(queryset=Post.objects.all().order_by("-date")[:25], 
				template_name="blog/blog.html")),
				url(r'^(?P<pk>\d+)$', DetailView.as_view(model = Post, 
				template_name = 'blog/post.html')),
				url(r'^add_category/$', views.add_category, name="add_category"),
				url(r'^category/(?P<category_name_url>\w+)$', views.category, name='category'),
				url(r'^like_category/$', views.like_category, name='like_category'),
				url(r'^suggest_category/$', views.suggest_category, name='suggest_category')

			]
    

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('personal.urls')),
    url(r'^blog/', include('blog.urls')),
    url(r'^register/', include('register.urls')),

]

personal/urls.py
from django.conf.urls import url, include
from . import views


urlpatterns = [
   
    url(r'^$',views.index, name="index"),
    url(r'^contact/$', views.contact, name="contact"),
   
    
]

blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Post(models.Model):
	title = models.CharField(max_length=140)
	body =  models.TextField()
	date = models.DateTimeField()
	image = models.ImageField(upload_to="blog/uploads/", blank=True)
	website = models.URLField(blank=True)
	#website = models.URLField(max_length=50, default='')


	#def __unicode__(self): #python2
	def __str__(self): #python3
		return self.title


class Category(models.Model):
	name = models.CharField(max_length=128, unique=True)
	
	def __str__(self):
		return self.name


class Page(models.Model):
	category = models.ForeignKey(Category)
	title = models.CharField(max_length=128)
	url = models.URLField()
	views = models.IntegerField(default=0)

	def __str__(self):
		return self.title

		

personal/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

personal/forms.py
from django import forms
from blog.models import Page, Category

class CategoryForm(forms.ModelForm):
	name = forms.CharField(max_length=128, help_text="Please enter the category name.")
	views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
	likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

	#An inline class to provide additional information on the form.

	class Meta:
	 	#provide an association between the ModelForm and a model
	 	model =  Category
	 	fields = ['name'] # This is for an array or use '__all__' or ('name',) for a tuple

class PageForm(forms.ModelForm):
	title = forms.CharField(max_length = 128, help_text ="PLease enter the title of the page.")
	url = forms.URLField(max_length=200, help_text= "Please enter the URL of the page.")
	views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

	class Meta:
		#provide an association between the ModelForm and a model
		model = Page
		# What fields do we want to include in our form?
		# This way we dont need every field in the model present
		# Some fields may allow Null values, so we may not want to include them....
		# Here, we are hiding the foreign key.
		fields = ('title','url','views')

personal/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render


# Create your views here.
def index(request):
 	return render(request, "personal/home.html")

def contact(request):
	return render(request, "personal/basic.html", {'hannington': ['If you want to text me, send a message here', 'naamarahannz@gmail.com']})

personal/templates/personal/basic.html
{% extends "personal/header.html" %}

{% block content %}
	{% for hans in hannington %}
		<p>{{hans}}</p>
	{% endfor %}


{% endblock %}

personal/templates/personal/gadget.html
{% load social_widgets %}
<div class= "event">
{% load instagram_client %}

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.5&appId={APP_ID}";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<a class="twitter-timeline" data-width="330" data-height="500" href="https://twitter.com/NaamaraHanningt?ref_src=twsrc%5Etfw">Tweets by NaamaraHanningt</a> <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>




<div class="fb-page" 
     data-href="https://www.facebook.com/SoftProgUganda/" 
     data-tabs="timeline" 
     data-small-header="false" 
     data-adapt-container-width="true" 
     data-hide-cover="false" 
     data-show-facepile="true">
  <div class="fb-xfbml-parse-ignore">
    <blockquote cite="https://www.facebook.com/facebook">
      <a href="https://www.facebook.com/facebook">Facebook</a>
    </blockquote>
  </div>
</div>


</div>

personal/templates/personal/header.html
{% load staticfiles %}

{% if user.is_authenticated %}
<h1>welcome {{ user.username }}! <h1>
Thanks for taking your time to be part of us <br />
<button data-catid="{{category.id}}" data-title="{{ result.title }}" data-url="{{ result.link }}" class="register-add btn btn-mini btn-info" type="button">Add</button><br />

<a href="register/restricted">Restricted page</a> <br>
<a href="register/logout">Logout</a>

{% else %}



<!DOCTYPE html>
<html>
<head>
	<title>Naamara Hannington</title>
	<meta charset="utf-8"/>
	
	<link rel="stylesheet" type="text/css" href="{% static 'personal/css/bootstrap.min.css'%}">
	<!--<link rel="stylesheet" type="text/css" href="{% static 'personal/css/bootstrap.css'%}"> -->
	<script type="text/javascript" src ="{% static 'personal/js/register-ajax.js' %}"></script>
	<script src ="{% static 'personal/js/jquery.js' %}"></script>  
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<!-- Start WOWSlider.com HEAD section -->
	<link rel="stylesheet" type="text/css" href="styles/style.css" />
	<script type="text/javascript" src="http://code.jquery.com/jquery-1.7.2.min.js"></script>
	<!-- End WOWSlider.com HEAD section -->
	<style type ="text/css">
		html,body{
			height:100%;
		}
	</style>


</head>
<body class="body" style="background-color: #f6f6f6">
	<div class="container-fluid" style="min-height:95%; ">
		<div class="row">
			<div class="col-sm-2">
				<br>
				<center>
					<img src="{% static 'personal/images/home.png' %}" class="img-responsive" style="max-height: 100px;" alt="face">
				</center>
			</div>
			<div class="col-sm-10">
				<br>
				<center>
					<h1>Programming, Teaching, Entrepreneurship</h1>
				</center>
			</div>
		</div>

		<div class="row">
			<div class="col-sm-2">
			<br>
			<br>
			<!-- Great, till you resize-->
			<!-- <div class="well bs-sidebar affix" id="sidebar" style="background-color:#fff">-->
			<div class="well bs-sidebar affix" id="sidebar" style="background-color:#fff">
				<ul class="nav nav-pills nav-stacked">
					<li><a href="/">Home</a></li>
					<li><a href="/blog/add_category">Add Category</a></li>
					<li><a href="/blog">Blog</a></li>
					<li><a href="/contact">Contact</a></li>
					<li><a href="/register/register">Register here</a></li>
					<li><a href="/register/login">Login</a></li>
				</ul>

				<ul class="nav nav-list">
					<li class="nav-header">Find a Category</li>
						<form>
							<label></label>
								<li><input class="search-query span10" type="text" name="suggestion" value="" id="suggestion" /></li>
						</form>
				</ul>
		{% if cat_list %}
				<div id="cats">
					{% include 'register/category_list.html' with cat_list=cat_list %}
				</div>
		{% endif %}
			</div> <!-- well ba-sidebar affix-->

			</div> <!-- col-sm-2 -->
			<div class="col-sm-10">
				<div class="container-fluid">
					<br><br>
					{% block content%}
					{% endblock %}
				</div> <!-- container-fluid -->
			</div> <!-- col-sm-10-->

		</div> <!-- row -->
	</div>
	<footer>
		<div class="container-fluid" style="margin-left: 15px;">
			<p><a href="#" target="blank">Contact</a> | <a href="#" target="blank">Linkedln</a> | <a href="#" target="blank">Google+</a></p>
		</div><!-- container fluid -->
	</footer>
</body>

</body>
</html>

{% endif %}

personal/templates/personal/home.html
{% extends "personal/header.html" %}
{% load staticfiles%} 
{% load social_widgets %}

{% block content %}


			<!-- Start WOWSlider.com BODY section
	<div id="wowslider-container">
	<div class="ws_images"><ul>
	<li><a href="http://www.wowslider.com/index.html#overview"><img src="{% static 'personal/images/slide1new.jpg' %}" title="" id="wows_0"/></a></li>
	<li><a href="http://www.wowslider.com/demo.html"><img src="{% static 'personal/images/slide2new.jpg' %}" alt="You can add description to slides!" title="You can add description to slides!" id="wows_1"/></a></li>
	<li><a href="http://www.wowslider.com/index.html#download"><img src="{% static 'personal/images/slide3new.jpg' %}" alt="" title="" id="wows_2"/></a></li>
	<li><a href="http://www.wowslider.com/index.html#download"><img src="{% static 'personal/images/slider4new.png' %}" alt="" title="" id="wows_2"/></a></li>
	</ul></div>
	<div class="ws_bullets"><div>
	<a href="#" title=""><img src="{% static 'personal/tooltips/slide1new.jpg' %}" alt=""/>1</a>
	<a href="#" title="You can add description to slides!"><img src="{% static 'personal/tooltips/slide2new.jpg' %}" alt="You can add description to slides!"/>2</a>
	<a href="#" title=""><img src="{% static 'personal/tooltips/slide3new.jpg' %}" alt=""/>3</a>
	<a href="#" title=""><img src="{% static 'personal/tooltips/slider4new.png' %}" alt=""/>4</a>
	</div></div>
		<a href="#" class="ws_frame"></a>
		<div class="ws_shadow"></div>
	</div>
	<script type="text/javascript" src="{% static 'personal/js/wowslider.js' %}"></script>
	<script type="text/javascript" src="{% static 'personal/js/script.js' %}"></script>
	 End WOWSlider.com BODY section -->
	
		<iframe width="560" height="315" src="https://www.youtube.com/embed/weeI1G46q0o" frameborder="0" gesture="media" allow="encrypted-media" allowfullscreen></iframe>

<div id=gadget>
<h2 style="background-color: rgb(184, 198, 213);">SOCIAL MEDIA GADGETS</h2>
  {% include 'personal/gadget.html' %}


</div>

{% include "personal/includes/feedback.html" %}

{% endblock %}